version: '3.9'
services:
  dev-db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sec123
      POSTGRES_DB: nest_contactbook
